version: "3"

services:
  postgres_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root*123
    ports:
      - 5432:5432
    container_name: postgres_db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8010:8080
    container_name: asira_adminer
    hostname: "adminer.local"

  portainer:
    image: portainer/portainer
    container_name: "portainer-manager"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: -H unix:///var/run/docker.sock --no-auth
    ports:
      - 9000:9000

networks:
  default:
    external:
      name: moovaz
